import Head from "next/head";
import Image from "next/image";
import Question from "../components/question";
import styles from "../styles/Home.module.css";
import { useEffect, useState, useContext } from "react";
import AuthContext from "../context/auth";
import { useRouter } from "next/router";
import Link from "next/link";

export default function Home() {
  const [loading, setLoading] = useState(false);
  const authContext = useContext(AuthContext);
  const router = useRouter();
  useEffect(() => {
    if (!authContext.user) {
      router.push("/login");
    }
    const load = async () => {
      const res = await fetch("/api/question/questions");
      const data = await res.json();
      setQuestions({ index: 0, data: data });
      setLoading(true);
    };
    load();
  }, []);

  const [questions, setQuestions] = useState({ index: 0, data: [] });
  return (
    <div className={styles.container}>
      <Head>
        <title>Less bullying, more Happiness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={`${styles.header} ${styles.grid1}`}>
        <Image
          className={styles.logoApp}
          src="/logo.png"
          alt="Less bullying, more Happiness"
          width={80}
          height={80}
        />
        <div>
          <Link className={styles.button1} href={"/logout"}>Log out</Link>
        </div>
      </header>

      <main className={styles.main}>
        {loading ? (
          questions.data.length > 0 &&
          questions.index < questions.data.length ? (
            <>
              <Question
                _id={questions.data[questions.index]._id}
                question={questions.data[questions.index].question}
                nextQuestion={() => {
                  setQuestions({ ...questions, index: questions.index + 1 });
                }}
                user={authContext.user}
              />
            </>
          ) : (
            <>
              <h1>¡Gracias!</h1>
              <Link className={styles.button1} href="/">Salir</Link>
            </>
          )
        ) : (
          <></>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
