import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Less bullying, more Happiness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={`${styles.header} ${styles.grid1}`}>
        <Link href="/">
          <Image
            className={styles.logoApp}
            src="/logo.png"
            alt="Less bullying, more Happiness"
            width={80}
            height={80}
          />
        </Link>
        <div className={styles.grid2}>
          <Link href="/login" className={styles.button1}>
            Log In
          </Link>
          <Link href="/signup" className={styles.button2}>
            Sign Up
          </Link>
        </div>
      </header>

      <main className={styles.main}>
        <div className={styles.grid}>
          <h1 className={styles.title}>Welcome to:</h1>
          <h2 className={styles.title}>
            <a>Less bullying, more Happiness</a>
          </h2>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
