import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Signup.module.css";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Login() {
  const [form, setForm] = useState({
    name: "",
    lastname: "",
    anonymous: false,
    email: "",
    password: "",
    confirmPass: "",
  });

  const router = useRouter();

  const handlerSubmit = async (e) => {
    e.preventDefault();
    if (
      form.name.length > 0 &&
      form.lastname.length > 0 &&
      form.email.length > 0 &&
      form.password.length > 0 &&
      form.confirmPass.length > 0
    ) {
      if (form.password == form.confirmPass) {
        const formatForm = {
          name: form.name,
          lastname: form.lastname,
          anonymous: form.anonymous,
          email: form.email,
          pass: form.password,
        };
        const req = await fetch("/api/auth/signup", {
          method: "POST",
          body: JSON.stringify({ user: formatForm }),
          headers: {
            "Content-Type": "application/json",
          },
        });
        const res = await req.json();
        if (res.success) {
          router.push("/login");
        } else {
          alert("Some fields are incorrect");
        }
      } else {
        alert("Passwords don't match");
      }
    } else {
      alert("Please fill all the fields");
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Less bullying, more Happiness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={`${styles.header} ${styles.grid1}`}>
        <Link href="/">
          <Image
            className={styles.logoApp}
            src="/logo.png"
            alt="Less bullying, more Happiness"
            width={80}
            height={80}
          />
        </Link>
      </header>

      <main className={styles.main}>
        <div className={styles.grid}>
          <h1 className={styles.title}>Sign Up:</h1>
          <form className={styles.form} onSubmit={handlerSubmit}>
            <label className={styles.label1}>Name:</label>
            <input
              className={styles.input1}
              type="text"
              placeholder="Name"
              required
              value={form.name}
              onChange={(e) => {
                setForm({ ...form, name: e.target.value });
              }}
            />
            <label className={styles.label2}>Lastname:</label>
            <input
              className={styles.input2}
              type="text"
              placeholder="lastname"
              required
              value={form.lastname}
              onChange={(e) => {
                setForm({ ...form, lastname: e.target.value });
              }}
            />
            <label className={styles.label3}>anonymous?</label>
            <input
              className={styles.input3}
              type="checkbox"
              required
              value={form.anonymous}
              onChange={(e) => {
                setForm({ ...form, anonymous: e.target.value });
              }}
            />
            <label className={styles.label4}>Email:</label>
            <input
              className={styles.input4}
              type="email"
              placeholder="Email"
              required
              value={form.email}
              onChange={(e) => {
                setForm({ ...form, email: e.target.value });
              }}
            />
            <label className={styles.label5}>Password:</label>
            <input
              className={styles.input5}
              type="password"
              placeholder="Password"
              required
              value={form.password}
              onChange={(e) => {
                setForm({ ...form, password: e.target.value });
              }}
            />
            <label className={styles.label6}>Confirm Pass:</label>
            <input
              className={styles.input6}
              type="password"
              placeholder="Confirm password"
              required
              value={form.confirmPass}
              onChange={(e) => {
                setForm({ ...form, confirmPass: e.target.value });
              }}
            />
            <button className={styles.button1}>Sign Up</button>
            <p className={styles.p}>
              Already have an account?{" "}
              <Link href="/login" className={styles.link}>
                Log In
              </Link>
            </p>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
